server:
  port: 8877

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_codingbat
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

application:
  jwt:
    secretKey: 31321Jwt21cret76575646Key131231wt21cret76575646Key1312311321Jwt21cret76575646Key131231wt21cret76575646Key131231
    accessTokenExp: 86400000 # a day
    refreshTokenExp: 24096000000 # 7 days
