package uz.pdp.app_codingbat.config.core;

public interface BaseURI {

    String DOC_OPEN_API = "/v3/api-docs/**";
    String DOC_SWAGGER_API = "/swagger-ui/**";
    String DOC_SWAGGER_UI_F = "/swagger-ui.html";
    String DOC_SWAGGER_UI = "/swagger-ui.html";

    String API1 = "/api/v1";
    String API2 = "/api/v2";
    String ALL = "/all";
    String ALL_URLS = "/**";
    String PING = "/ping";
    String USER = "/user";
    String SECURITY = "/security" ;
    String SEARCH = "/search";
    String BELT = "/belt";
    String PERSON_APPLICATION = "/person/application";
    String LOAN_APPLICATION = "/loan/application";
    String ROLE = "/role";
    String PERMISSION = "/permission";
    String ONE = "/one";
    String CURRENT = "/current";
    String STATUS = "/status";
    String LIST = "/list";
    String REGISTRATION = "/registration";

    String SIGN_IN = "/sign-in";
    String SIGN_UP = "/sign-up";
    String CHECK = "/check";
    String VERIFY = "/verify";
    String ACTIVATE = "/activate";
    String IN = "/in";
    String UP = "/up";
    String IDENT = "/ident";
    String MAIN = "/main";
    String ALTER = "/alter";
    String PASSWORD = "/password";
    String CODE = "/code";
    String RESEND = "/resend";
    String RESET = "/reset";
    String CHANGE = "/change";

    String AUTH = "/auth";
    String TOKEN = "/token";
    String PREPARE = "/prepare";
    String INIT = "/init";
    String CONFIRM = "/confirm";
    String VALIDATE = "/validate";
    String REFRESH = "/refresh";
    String SIMPLE = "/simple";
    String DELETE = "/delete";
    String AGREEMENT = "/agreement";
    String EMAIL = "/email";
    String FILE = "/file";
    String FILES = "/files";
    String UPLOAD = "/upload";
    String MINIO = "/minio";
    String PREVIEW = "/preview";
    String DOWNLOAD = "/download";
    String CATEGORY = "/category";
    String PRODUCT = "/product";
    String NOTIFICATION = "/notification";
    String DEVICE = "/device";
    String TRUSTED = "/trusted";
    String BRANCH = "/branch";
    String NEWS = "/news";
    String DISTANCE = "/distance";
    String AGENT = "/agent";
    String REFERENCE = "/reference-book";
    String PROFESSIONALACTIVITY = "/professional_activity";
    String VERSION = "/version";
    String PAGE = "/page";
    String BANNER = "/banner";
    String GET_BY_ID = "/get-by-id";
    String GET_BY_ = "/get-by-";
    String FAILED = "/failed";
    String CALCULATE = "/calculate";
    String STATEMENT = "/statement";
    String STATISTICS = "/statistics";
    String RESULT = "/result";
    String REVISION = "/revision";
    String ME = "/me";
    String UPDATE = "/update";
    String ADD = "/add";
    String LOAN = "/loan";
    String SCHEDULE = "/schedule";
    String TRANSLATE = "/translate";
    String FAQ = "/faq";

    String READ = "/read";
    String PROFILE = "/profile";
    String ADMIN = "/admin";
    String CHAT = "/chat";
    String LEAD = "/lead";
}
